103 mongodb impl
slavoyar/database-monitoring pull request #121
Opened 2023-06-01 14:04 UTC by Batiskaaaf

Добавил NotificationService (без тестов!)

2023-06-01 17:52 UTC, slavoyar requested changes

2023-06-01 17:52 UTC, slavoyar commented on src/Services/Notification/Notification.Infrastructure/Services/NotificationService.cs
> +        if (groups.Any(n => n.Key == true))
Можно просто ```groups.Any(n => n.Key)```

2023-06-01 17:52 UTC, slavoyar commented on src/Services/Notification/Notification.Infrastructure/Services/NotificationService.cs
> +        return result.Select(n => new NotificationDto { Id = n.Id, Data = n.Data });
Может надо добавить NotificationDate для сортировке на фронте?

2023-06-05 10:47 UTC, Batiskaaaf commented on src/Services/Notification/Notification.Infrastructure/Services/NotificationService.cs
> +        if (groups.Any(n => n.Key == true))
Поправил

2023-06-05 10:47 UTC, Batiskaaaf commented on src/Services/Notification/Notification.Infrastructure/Services/NotificationService.cs
> +        return result.Select(n => new NotificationDto { Id = n.Id, Data = n.Data });
Добавлено

2023-06-05 15:20 UTC, slavoyar approved these changes

2023-06-05 15:20 UTC, merged