160 subscribe to workspace events
slavoyar/database-monitoring pull request #162
Opened 2023-06-29 18:11 UTC by Batiskaaaf

Подписался на уведомления от сервиса рабочих пространств, сделал общий хэндлер от которого наследуются все остальные, так как логика очень простая

2023-07-02 11:42 UTC, Evgen-Kost approved these changes

2023-07-02 11:44 UTC, Batiskaaaf commented
не пульте тут трабл какой то, поправлю позже

2023-07-02 11:45 UTC, Evgen-Kost requested changes
--не пульте тут трабл какой то, поправлю позже
исправить трабле

2023-07-02 11:49 UTC, Batiskaaaf commented
поправил пуляйте

2023-07-06 08:48 UTC, Evgen-Kost approved these changes

2023-07-06 08:48 UTC, merged