1) Add project for TestPatient
slavoyar/database-monitoring pull request #173
Opened 2023-07-22 12:14 UTC by Evgen-Kost

# Сделано

- [#172 ] Создание искусственных логов

1) Add project for TestPatient
2) Upgrade docker-compose to shorter names
3) Upgrade docker-compose to run testPatient
4) To collect logs you need to run controller method (FireAndForget Job or Recurring Job)

2023-07-24 20:20 UTC, slavoyar requested changes

2023-07-24 20:20 UTC, slavoyar commented on src/docker-compose.yml
> +  testpatient-1:
Я думаю можно выделить в отдельный docker-compose файл все контейнеры с пациентами, так как они не часть нашей системы. Тогда будет удобнее отдельно поднимать сервис и пациентов.

2023-07-24 20:20 UTC, slavoyar commented on src/Services/TestPatient/Controllers/LogsController.cs
> +        [Route("GetLogs")]
Просто logs, так как уже рест метод get

2023-07-24 20:20 UTC, slavoyar commented on src/Services/TestPatient/Controllers/LogsController.cs
> +        public async Task<IActionResult> GetLogs()
Нам вроде не все нужны, а только последнии, которые нами не были обработаны. Надо добавить параметр - время передачи последнего лога. И отдавать логи только отталкиваясь от этого времени.

2023-07-24 20:20 UTC, slavoyar commented on src/Services/TestPatient/Models/LogsModel.cs
> +        public string? ReceivedAt { get; set; }
Думаю достаточно параметра CreatedAt - дата, когда создан лог. А RecievedAt должен быть только в Agregation сервисе.

2023-07-25 17:37 UTC, Evgen-Kost reviewed
Изменения добавлены в ветку 172-ArtificialLogs

2023-07-26 19:11 UTC, slavoyar approved these changes

2023-07-26 19:11 UTC, merged