[#60] Add user service
slavoyar/database-monitoring pull request #180
Opened 2023-07-31 21:31 UTC by slavoyar

# Сделано
- [x] Произведен рефакторинг сервиса авторизации: Добавлен claim с email, удалены контроллеры Workspace, Admins
- [x] Добавлены рест методы для получения, редактирования и удаления пользователей
- [x] Добавлена возможность менять настройки пользователя
- [x] Добавлено обновление access токена при ошибке авторизации
- [x] Настроен прокси для контроллеров

2023-08-01 14:41 UTC, Evgen-Kost requested changes
1) В docker compose задублировался в зависимостях elasticsearch и kibana
2) указано "Добавлена возможность менять настройки пользователя", но при попытке запуска из докера и изменения настройки пользователя - падает ошибка PATCH http://localhost/api/users/update 400 (Bad Request)

2023-08-02 17:14 UTC, Evgen-Kost requested changes
1) /api/Users/info , описание Get user with input mail , но ввести свой email нельзя , в Delete передается, в этот Get нет
2) Сейчас /api/Auth/login возвращает вообще все параметры пользователя, аля emailConfirmed и accessFailedCount, предлагаю урезать все, что не нужно для фронта

2023-08-02 17:44 UTC, slavoyar commented
> 1. /api/Users/info , описание Get user with input mail , но ввести свой email нельзя , в Delete передается, в этот Get нет
> 2. Сейчас /api/Auth/login возвращает вообще все параметры пользователя, аля emailConfirmed и accessFailedCount, предлагаю урезать все, что не нужно для фронта

1. Изменил описание метода. Я предполагаю, что этот метод может использоваться только текущим пользователем, поэтому беру данные из клэймов.
2. Изменил тип на AuthUpdateModel, где представлены данные, которые актуальны только для фронта. Возможно надо будет потом название поменять.

2023-08-02 18:54 UTC, Evgen-Kost approved these changes

2023-08-02 18:54 UTC, merged