[#59] Add workspace service
slavoyar/database-monitoring pull request #188
Opened 2023-08-04 20:22 UTC by slavoyar

# Сделано
- [x] Добавлено создание, обновление и удаление воркспейсов
- [x] Добавлено получение всех воркспейсов
- [ ] Добавлено получение воркспейсов для пользователя

Close #59

2023-08-05 14:36 UTC, Evgen-Kost requested changes
действия в докере - 
1) При переходе на страницу http://localhost/admin/workspaces просто белый экран, 500 error ( i.map is not a function )
2) Workspace/UsersByServerId возвращает пустоту 
3) При первичной миграции БД, чтобы при показе проекта не пришлось руками при всех создавать эти детали, предлагаю создавать первичный workspace
 ( name = Аналитика , 
 description = Аналитика и Кибербезопасность, 
 users = наш стандартный админ, 
 servers = пациенты, которые появятся в Aggregation 
# testpatient1 d69cd87f-1f08-4b12-af16-980b003cdc5f
# testpatient2 d13920a2-4961-43cc-bd22-12187b19f512
# testpatient3 8d8a6029-676a-4e09-91c5-32c56602f67f

2023-08-06 22:01 UTC, slavoyar commented
> действия в докере -
> 
> 1. При переходе на страницу http://localhost/admin/workspaces просто белый экран, 500 error ( i.map is not a function )
> 2. Workspace/UsersByServerId возвращает пустоту
> 3. При первичной миграции БД, чтобы при показе проекта не пришлось руками при всех создавать эти детали, предлагаю создавать первичный workspace
>    ( name = Аналитика ,
>    description = Аналитика и Кибербезопасность,
>    users = наш стандартный админ,
>    servers = пациенты, которые появятся в Aggregation
> 
> # testpatient1 d69cd87f-1f08-4b12-af16-980b003cdc5f
> # testpatient2 d13920a2-4961-43cc-bd22-12187b19f512
> # testpatient3 8d8a6029-676a-4e09-91c5-32c56602f67f

1. Исправил
2. Этот метод не используется на фронте, можно не исправлять пока. Задачу добавил: #190 
3. Добавлю при реализации сервиса для агрегации

2023-08-07 04:43 UTC, Evgen-Kost requested changes
Докер :
Страница с workspace открывается, при попытке добавить workspace 
rtk-query.esm.js:166     GET http://localhost/api/users 404 (Not Found)
rtk-query.esm.js:166     GET http://localhost/api/users/info 404 (Not Found)
rtk-query.esm.js:166     POST http://localhost/api/v1/workspace 400 (Bad Request)
подозреваю что внутри localhost прописан, не имя сервиса из докера

2023-08-07 17:44 UTC, Evgen-Kost approved these changes

2023-08-07 17:44 UTC, merged