198 rework event sending logick
slavoyar/database-monitoring pull request #199
Opened 2023-08-15 11:02 UTC by Batiskaaaf

Теперь ивенты создаются и при изменении воркспейса

2023-08-18 16:34 UTC, slavoyar requested changes

2023-08-18 16:34 UTC, slavoyar commented on src/Services/Workspace/appsettings.json
> +    "ConnectionString": "Server=localhost;Port=5432;Username=postgres;Password=admin;Database=Workspace;Pooling=true;TrustServerCertificate=True"
Зачем изменено, у БД для воркспейсов порт 5433.
![image](https://github.com/slavoyar/database-monitoring/assets/37935471/1d692bfe-3085-4044-aaa3-ea30946fa2a5)

2023-08-18 16:34 UTC, slavoyar commented on src/Services/Workspace/Services/Implementation/WorkspaceService.cs
> +        // await ReplaceEntities(workspace.Users, workspaceDto.Users, unitOfWork.Users, workspace);
Зачем оставллять старый код в комментариях, если этот метод удален?

2023-08-18 16:34 UTC, slavoyar commented on src/Services/Workspace/ApplicationEvents/ApplicationEventService.cs
> +    public Task PublishThroughEventBus(BaseEvent @event)
Зачем тут использовать Task?

2023-08-18 16:38 UTC, Batiskaaaf commented on src/Services/Workspace/appsettings.json
> +    "ConnectionString": "Server=localhost;Port=5432;Username=postgres;Password=admin;Database=Workspace;Pooling=true;TrustServerCertificate=True"
Потому что стандартный порт постгре 5432. Что бы проще было дебажить я поменял порт на стандартный. Все равно при запуске контейнера порт поменяется, так что это просто для удобства

2023-08-18 16:40 UTC, Batiskaaaf commented on src/Services/Workspace/ApplicationEvents/ApplicationEventService.cs
> +    public Task PublishThroughEventBus(BaseEvent @event)
Ну из за того что у нас сразу может запаблишиться хоть 10 ивентов, что может занять время, что бы программа на месте не стала в этот момент, сделал метод асинхронным

2023-08-18 17:12 UTC, slavoyar commented on src/Services/Workspace/appsettings.json
> +    "ConnectionString": "Server=localhost;Port=5432;Username=postgres;Password=admin;Database=Workspace;Pooling=true;TrustServerCertificate=True"
Почему для дебага не исползовать постгре из докера. Можно только его поднять 
```
docker compose up workspace-postgre
```

Или, если вместе с другими сервисами тестить, то вообщем проблем нет

2023-08-18 17:16 UTC, slavoyar commented on src/Services/Workspace/ApplicationEvents/ApplicationEventService.cs
> +    public Task PublishThroughEventBus(BaseEvent @event)
В таком случае не надо await писать в UpdateWorkspaceAsync, так как отрпавка каждого ивенат блокирует отпраку остальных, хотя нам не важен порядок.

2023-08-20 18:19 UTC, Batiskaaaf commented on src/Services/Workspace/appsettings.json
> +    "ConnectionString": "Server=localhost;Port=5432;Username=postgres;Password=admin;Database=Workspace;Pooling=true;TrustServerCertificate=True"
Ну удобней ведь на своём компе бд запустить, да и этот порт не влияет на работу программы в докере

2023-08-20 18:20 UTC, Batiskaaaf commented on src/Services/Workspace/ApplicationEvents/ApplicationEventService.cs
> +    public Task PublishThroughEventBus(BaseEvent @event)
Я не могу сейчас изменить и проверить будет ли работать, сейчас не дома и буду только 24, так что предлагаю оставить.

2023-08-20 18:22 UTC, slavoyar approved these changes

2023-08-20 18:23 UTC, merged